### ISSUE TITLE
Fail to execute insert to list function

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#104]
I'm trying to implement a function in MeTTa to insert an element in a sorted list but fails (on revision 067d627e708e9841f1cda9dcc2df479d809642eb).

Let's first check that conditional works
```metta
;; Implement conditional
(= (if True $x $y) $x)
(= (if False $x $y) $y)

;; Test conditional
!(println! (if True 42 0))
!(println! (if False 42 0))
```
It outputs
```
42
0
```
as it should.

Then let's test if insert works (using the previously implemented conditional)
```metta
;; Declare List data structure
(: List (-> $a Type))
(: Nil (List $a))
(: Cons (-> $a (List $a) (List $a)))

;; Implement insert element in a presumably sorted list
(= (insert $x Nil) (Cons $x Nil))
(= (insert $x (Cons $head $tail)) (if (< $x $head)
                                      (Cons $x (Cons $head (Cons $tail)))
                                      (Cons $head (insert $x $tail))))

;; Test insert
!(println! (insert 1 Nil))
!(println! (insert 1 (insert 2 Nil)))
```
It outputs
```
(insert 1 Nil)
(insert 1 (insert 2 Nil))
```
which is not correct.

I should mention that this used to work on revision 280d2310b9a198ba6420ae875f75aa359ad7e267.

**Comment by ngeiswei** [comment]
I have narrowed down the problem.  The following
```metta
;; Declare List data structure
(: List (-> $a Type))
(: Nil (List $a))
(: Cons (-> $a (List $a) (List $a)))

;; Partially implement insert element in a presumably sorted list
(= (insert $x Nil) (Cons $x Nil))

;; Test insert
!(println! (insert 1 Nil))
```
outputs
```
(insert 1 Nil)
```
which is incorrect.

However, removing the List data structure declaration, as follows
```metta
;; Partially implement insert element in a presumably sorted list
(= (insert $x Nil) (Cons $x Nil))

;; Test insert
!(println! (insert 1 Nil))
```
outputs
```
(Cons 1 Nil)
```
which is correct.

So the presence of the declaration, for some reason, seems to causing the problem.

**Comment by Necr0x0Der** [comment]
Yes, support of types is being reworked now (the interpreter now matches the expected type of the argument with the actual type), and support for polymorphic functions seems to be not fully implemented. This has just yesterday been selected as the next step of work on types.

**Comment by ngeiswei** [comment]
OK, thanks, so for now I can just ignore types, I suppose.

**Comment by Necr0x0Der** [comment]
I suppose we should add your example as a unit test (skipped for now).

**Comment by ngeiswei** [comment]
Sure, I suppose I can add it myself.

**Comment by ngeiswei** [comment]
The previous error was the result of a typo pointed by @vsbogd
