### ISSUE TITLE
Type definition interferes with beta-reduction

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#135]
The following code
```
;; Define TruthValue type
(: TruthValue Type)
(: PrCnt (-> Float Float TruthValue))

;; Define a formula
(= (formula True False) (PrCnt 0.0 1.0))

;; Test the formula
!(formula True False)
```
outputs
```
[(formula True False)]
```

meaning `(formula True False)` is not properly reduced.  However removing the type definition yields the desired result:

```
;; Define a formula
(= (formula True False) (PrCnt 0.0 1.0))

;; Test the formula
!(formula True False)
```
outputs
```
[(PrCnt 0.0 1.0)]
```

**Comment by ngeiswei** [comment]
That issue might, or not, be related to issue #130.

**Comment by Necr0x0Der** [comment]
I closed it. Thanks for reporting.

**Comment by ngeiswei** [comment]
BTW, something that is missing is some form of online help.  Maybe docstring support or such, but I suppose that'll come once we have a REPL.

**Comment by Necr0x0Der** [comment]
> Although I suppose a type error should have been raised
You can use `!(pragma! type-check auto)`. Although it doesn't seem to work right now for grounded types.

**Comment by Necr0x0Der** [comment]
> BTW, something that is missing is some form of online help. Maybe docstring support or such, but I suppose that'll come once we have a REPL.

Yes, sure. But it is of lower priority for now.
