### ISSUE TITLE
Nested imports raises exception

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#152]
# Problem
Importing a metta file that itself imports another metta file raises the exception
```
[(Error (import! &self B.metta) Exception caught:
AttributeError: 'list' object has no attribute 'catom')]
```

# How to reproduce
1. Create empty `A.metta` file
2. Create `B.metta` file with content `!(import! &self "A.metta")`
3. Create `C.metta` file with content `!(import! &self "B.metta")`
4. Running `metta.py C.metta` raises the exception, while neither `A.metta` nor `B.metta` does.

**Comment by Necr0x0Der** [comment]
Thanks. The problem seems to be not in nested imports, but in any execution (!) in the imported file.

**Comment by ngeiswei** [comment]
The problem seems to be fixed by #153 so I'm closing.

**Comment by ngeiswei** [comment]
I just want to see if merging #153 is gonna automatically close that issue so I'm reopening (and I should have waited for that branch to be merged before closing anyway).

**Comment by Necr0x0Der** [comment]
Yes, it was closed automatically.
