### ISSUE TITLE
Combining reduction and matching fails

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#165]
The following metta program
```clojure
(P Q)
(= (foo) P)
!(match &self ((foo) $Q) $Q)
```
outputs
```clojure
[]
```
instead of
```clojure
[Q]
```
as it should.

When replacing the match query by
```clojure
!(match &self (P $Q) $Q)
```
it outputs
```clojure
[Q]
```
as expected, indicating that the problem comes from the combination of reduction and matching.

**Comment by ngeiswei** [comment]
This is tested with the last revision 0a8ef1e46445760364322900c44eeb6d7b6a0752

I should mention that it used to work, thus the problem has been introduced somewhat recently.  I'll bisect the git history to see if I can find culprit commit.

**Comment by ngeiswei** [comment]
I can already say that the bug has been introduce between 1b4965a included and 0674bbc excluded.

**Comment by ngeiswei** [comment]
The culprit commit is 6ad3fb2.

**Comment by Necr0x0Der** [comment]
This is not a bug, but the intended behavior. `match` accepts `Atom` as a second argument in order for a programmer to be able to provide precise patterns without danger for them to be reduced. Now, if you want some parts of the pattern to be reduced, it should be done onside `match` expression, e.g.
```
(P Q)
(= (foo) P)
!(let $p (foo)
      (match &self ($p $Q) $Q))
```

**Comment by ngeiswei** [comment]
I see.  Thanks @Necr0x0Der.

I'm closing in that case.
