### ISSUE TITLE
Multiple type definitions cause multiple results

### ISSUE THREAD

**Issue by Necr0x0Der** [trueagi-io/hyperon-experimental#235]
Related to #188 , but a cleaner problem. The code
```
(: inc (-> Number Number))
(= (inc $x) (+ $x 1))
!(inc 1)
```
works as expected, but
```
(: inc (-> Number Number))
(: inc (-> Number Number))
(= (inc $x) (+ $x 1))
!(inc 1)
```
produces 4 (!) identical results. With equality non-determinism, the number of results multiplies. The interpreter works correctly, if the argument type doesn't match the (non-deterministic) type signature, e.g.
```
(: inc (-> Number Number))
(: inc (-> String Number))
(= (inc $x) (+ $x 1))
!(inc 1)
```
produces only one result. We don't have a settled semantics for non-deterministic types that match one equality. For example,
```
(: inc (-> Number Number))
(: inc (-> Atom Number))
(= (inc $x) (+ $x 1))
!(inc 1)
```
produces 2 results. There can be tricky cases, when we do want to use same equality interpreting its arguments as being of different types, and one may claim that getting 2 results in the latter case is OK (to be discussed and decided, I'd say; maybe, it would still be preferable to use the equality once, but to keep track of different possible types of its argument). But why there are 4 results for the duplicated type definition case?

**Comment by vsbogd** [comment]
One theoretical way to improve the situation is to not generate alternatives when required type is `%Undefined%` which means that any type works i.e. no type specifics is involved. In such case specific type doesn't add an information and alternative is just a duplicate. @Necr0x0Der what do you think?

**Comment by ngeiswei** [comment]
I see, I can live with that for now, so if the duplicate issue is too difficult to fix now I'm happy to have that merged.

**Comment by Necr0x0Der** [comment]
Can the use of type information be viewed not as generating alternatives, but filtering out them - not just for `%Undefined%`, but for all type signatures?
