### ISSUE TITLE
Centralized implementation for Space to track Observers

### ISSUE THREAD

**Issue by luketpeterson** [trueagi-io/hyperon-experimental#287]
Currently observers are registered with spaces using the trait method `Space::register_observer`.  This means each space implementation is responsible for keeping track of all observers, notifying each individually, and making sure they are correctly unregistered if they've been dropped (RefCount reached 0), etc.

We propose centralizing this logic to reduce code duplication and cut down on the possibility of errors / inconsistent treatment of observers.

https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185053077

Also, implement https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185650329 at the same time.

Additionally, we probably want to support `Clone` for the new common space object.  However, that object should not clone the observers.  https://github.com/trueagi-io/hyperon-experimental/pull/284#issuecomment-1534150664

Finally, on the C side, we should implement space_observer_get_payload().  After the Rust changes are made, the API could be refactored so that that `space_observer_new` doesn't exist, and `space_register_observer()` takes the arguments currently given to `space_observer_new`.  Then `space_register_observer()` would return a `space_observer_t` which could implement the `space_observer_get_payload()` function.  https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1184909631 for reference.

**Comment by luketpeterson** [comment]
Rust, unlike most object-oriented languages, doesn't provide the ability for superclasses (traits) to have their own storage.  This means we have two options.
1.) A common Space struct, containing an owned dyn trait object to implement all the specific functionality.
2.) A Space trait that has methods to create and access a common object.

It's hard to have a strong opinion because I haven't seen complex enough systems with multiple spaces to have a good idea of how multiple spaces might be managed.  2.) is more like the current code structure, so the safe option is to stick with that.

**Comment by vsbogd** [comment]
To keep the story of a decision I am adding the link to the discussion about using a pair of methods `register/unregister` as a possible way to go. See https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1183329585 part (2) and answers https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185053077 and https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185652608. The pair of methods also suffers from the absence of storage in a Rust trait (explained above https://github.com/trueagi-io/hyperon-experimental/issues/287#issuecomment-1535646425) , so this option loses the simplicity advantage.

**Comment by luketpeterson** [comment]
>> 1.) A common Space struct
> ... into separate SpaceObservable trait. The we can introduce struct SpaceImpl which is constructed from Space and implements both: Space and SpaceObservable. 

We could also just implement `register_observer` as a concrete implementation on the `SpaceImpl`.  Also personally I might call it `SpaceObj` or `SpaceContainer` or something.  Because it isn't a type that has implemented `Space`.  Sorry to be a pedant :-P

The downside to Option 1. is that everywhere that currently uses an `&dyn Space` needs to start using an &SpaceImpl.  But it's otherwise very straightforward.

2.) A Space trait that has methods to create and access a common object.

Sorry if my description was confusing.  Sometimes code is more precise than English.  I was thinking something along these lines:
```rust
pub struct SpaceCommon {
    observers: RefCell<Vec<Weak<RefCell<dyn SpaceObserver>>>>,
}
impl SpaceCommon {
    pub fn new() -> Self {
        Self {observers: RefCell::new(vec![])}
    }
    fn register_observer(&self, observer: Rc<RefCell<dyn SpaceObserver>>) {
        self.observers.borrow_mut().push(Rc::downgrade(&observer) as Weak<RefCell<dyn SpaceObserver>>);
    }
}

/// Read-only space trait.
pub trait Space {
    /// Registers space modifications `observer`. Observer is automatically
    /// deregistered when `Rc` counter reaches zero. See [SpaceObserver] for
    /// examples.
    /// NOTE: Implementors of Space should not override this default implementation
    fn register_observer(&self, observer: Rc<RefCell<dyn SpaceObserver>>) {
        self.common().register_observer(observer)
    }

    /// A SpaceCommon object managed by the Space
    fn common(&self) -> &SpaceCommon;
```

The advantage to this approach is that the outward-facing API of the Space trait doesn't need to change.  However, It means every Space implementor needs to carry around a SpaceCommon as part of their struct.

**Comment by luketpeterson** [comment]
Committed basic refactor in [ddb7bb8](https://github.com/luketpeterson/hyperon-experimental/commit/ddb7bb88387388840abe863ffa37b85ef61ba255)

However, there are some complications with https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185650329 that, on balance, mean it's probably not worth doing.

Specifically, I can't eliminate register_observer from the space trait completely, and make it part of the common implementation, as I originally hoped, because I can't return references out of the RefCell<dyn SpaceMut> container.  Since I can't take an argument with a generic type on a trait method of Space, I cannot give SpaceRef a generic type.

This means that dereferencing it (borrow / borrow_mut) would need a type argument, making it a lot less convenient to use.  Not to mention the loss of the ability to use non-'static observers with that approach.

Since the purpose of https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185650329 was to make the interface cleaner / easier to use, I don't think that change would be an overall win vs. the current code.

We can revisit this if/when we change the resource ownership pattern for Spaces.

**Comment by vsbogd** [comment]
> Specifically, I can't eliminate register_observer from the space trait completely, and make it part of the common implementation, as I originally hoped, because I can't return references out of the RefCell container. Since I can't take an argument with a generic type on a trait method of Space, I cannot give SpaceRef a generic type.

@luketpeterson, do you mean you cannot eliminate it because then it is not possible to implement `Space` for `DynSpace` or I got it wrong?

**Comment by vsbogd** [comment]
I am asking because to me it looks like the code in https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185650329 doesn't require returning references from `RefCell`, but may be I am missing something.

**Comment by luketpeterson** [comment]
> I am asking because to me it looks like the code in https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185650329 doesn't require returning references from RefCell

The issue is that it returns a SpaceObserverRef<T>, which can't be returned from a trait method if the trait is to remain object-safe.  (Because a vtable can't be built if the function signatures can change).  Technically, Rust could support it if the types were all the same size and had the same lifetimes, but unfortunately the languages just prohibits it outright.  It's one of those places where Rust is more strict than it needs to be.  Anyway, I added the work-around (FlexRef) in the c17c57a commit, and it's not too ugly as a short-term fix.

**Comment by vsbogd** [comment]
> The issue is that it returns a SpaceObserverRef, which can't be returned from a trait method if the trait is to remain object-safe. 

Aah, got it, the type parameter is not used in returned type at https://github.com/trueagi-io/hyperon-experimental/pull/284#discussion_r1185650329 this was confused me.

**Comment by luketpeterson** [comment]
This issue is fully addressed with https://github.com/trueagi-io/hyperon-experimental/pull/312
