### ISSUE TITLE
Introduce Char primary type

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#289]
The following
```
!(== 'A' "A")
!(get-type 'A')
!(get-type "A")
!("A")
```
outputs
```
[False]
[%Undefined%]
[String]
[('A')]
```
Indicating that even though "A" is displayed as 'A', the latter is neither a String nor a Char.

There are several fixes for that, the first one being to displaying "A" as "A".  In addition I would suggest to introduce a Char primary type that would be parsed with single quotes like traditional functional programming languages such as Haskell, Idris and Racket.

If you agree to that I don't mind taking care of it.

**Comment by vsbogd** [comment]
@ngeiswei , there is definitely some confusion. There are two reasons: the default way to print a string in Python is enclosing it into single quotes `'` and parsing rules for a quoted sequences of characters are hardcoded in Rust. 

When user runs a Python MeTTa interpreter both Python and Rust code works together. MeTTa parser (written in Rust) uses double quotes `"` to recognize a quoted sequence of characters as a token. Then the token is converted into a grounded string by the Python MeTTa standard library. Thus the resulting grounded atom is a Python object. The procedure of conversion to a string is written in Python. By default in Python string is printed using single quotes `'`. Before https://github.com/trueagi-io/hyperon-experimental/pull/266 it had been printed without quotes at all.

One issue here is that in Python we have a universal procedure to print all Python grounded atoms. And it uses single quotes for strings even when we know MeTTa accepts only double quoted sequences with spaces. Quick fix for this is to write a separate class to represent strings in Python and override the `__repr__()` method to print the string in double quotes. Also adding a single quoted character into Python and Rust MeTTa `stdlib` is trivial.

**Comment by vsbogd** [comment]
The more wider issue here is a bad decoupling of `Tokenizer` and `SExprParser`. Ideally there should be the only module responsible for a token recognition. But at the moment `SExprParser` does a part of the work by recognizing sequences of characters which are tokens, and `Tokenizer` specifies whether a sequence of characters is converted to a non-symbol atoms. In particular the `SExprParser` recognizes the double quoted sequences with spaces as tokens. This means `Tokenizer` which is configured by regular expressions cannot fully control how quoted character sequences are handled. The direct consequence is that one cannot add a single-quoted string (which includes spaces) by configuring the `Tokenizer`.

To fix this we need to combine `SExprParser` and `Tokenizer` to rule the process of parsing by tokens provided by the user. In such case the user can configure the tokens totally on a client side without modifying the code of parser. It means it is possible to configure single quoted strings or double quoted strings without harcoding the procedure inside the parser. But this fix will require more work on the Rust side and total rework of the parser. And it is a separate issue for sure.

**Comment by vsbogd** [comment]
@ngeiswei , I don't mind adding the character token, please feel free to fix it.
