### ISSUE TITLE
Variable equality is incorrectly applied in case of nested `let` expression

### ISSUE THREAD

**Issue by vsbogd** [trueagi-io/hyperon-experimental#290]
The following expression `!(let $f $x (let $f f $x))` being executed should return `[f]` but it returns `[$f#1]` instead.

To calculate the result property we should apply the equality of variables stated on the outer `let` (`{ $x = $f }`) to the nested `let` expression. Thus the nested `let` becomes `(let $x f $x)` or `(let $f f $f)` and finally evaluated to `f`.

The root cause is that `let` is implemented as a grounded operation. Grounded operation doesn't return `Bindings` and thus can only return values of the variables in the atoms. It does it applying `{ $x = $f }` to the `(let $f f $x)` but the result is `(let $x f $f)` because `Bindings` returns `$x` as a value for `$f` and `$f` as a value for `$x`. I omitted variable renaming here which leads to `$f` becomes `$f#1`. Finally `(let $x f $f)` is evaluated to `$f` because $f is absent in the pattern `$x`.

I would suggest fixing it through introducing a proper `let` implementation as a part of minimal interpreter implementation.

**Comment by vsbogd** [comment]
Raised #292 as a quick fix. I am not sure what is a proper fix though. 

When instance of `Bindings` contains equality for two or more variables we cannot just choose one and replace others by it. For example: `(let ($x $x) ($z $y) ($z $y))`, current code will replace it by `($z $y)` which is incorrect. Replacing both of them by `$x` or `$y` or `$z` doesn't reflect the result either. In fact we should return the equality of `$z` and `$y` as a result. And it is not possible with current `Grounding` API.

This issue was already discussed in https://github.com/trueagi-io/hyperon-experimental/issues/127#issuecomment-1454683688. But there I didn't take into account that grounded atom API restrictions doesn't allow handle this situation properly.

**Comment by ngeiswei** [comment]
Hmm, maybe `Binding` should have a MeTTa counterpart, that way the API wouldn't need to change and the semantics would be WISIWIG, as Greg likes to say.  I honestly do not know, but it's just crossing my head.

**Comment by ngeiswei** [comment]
So what should be the proper output of
```
(let ($x $x) ($z $y) ($z $y))
```
?  Maybe it could be all of them
```
[$x $y $z]
```
?

**Comment by vsbogd** [comment]
> Hmm, maybe Binding should have a MeTTa counterpart, that way the API wouldn't need to change and the semantics would be WISIWIG, as Greg likes to say.

We can do it relatively easy by representing the bindings as a grounded atom. In practice it means each operation inputs and outputs an additional value which keeps the variables' bindings. I don't see it changes something for the example above. Even without this change one can get the value of a variable by the variable name. What one cannot get from the bindings easily are the relations between variables (like equality of two variables). I am experimenting with the minimal set of MeTTa instructions to build the full MeTTa interpreter in MeTTa. I believe making bindings explicit will be much easier in such set. Then we can experiment with it.

**Comment by vsbogd** [comment]
When matching an atom and a pattern returns an instance of `Bindings` with variable equalities inside then it cannot be properly returned from grounded operations. For example when `(let $f $x (let $f f $x))` expression is executed the matching of `$f` and `$x` is `{ $f = $x }`. It is not properly applied to the nested `(let $f f $x)` because there was no priorities between variables and thus `$f` is replaced by `$x` and vice versa.

One possibility to fix that is to return an instance of `Bindings` `{ $f = $x }` from the `let` thus this variable equality will be later applied to properly match `(let $f f $x)`. But this requires modifying grounded functions API.

We also can represent the equality of variables as a variable renaming thus representing `{ $f = $x }` as `{ $x <- $f }` or `{ $f <- $x }`. Both forms seems to be equivalent but they are not. Here `$f` is a local variable from `let`'s pattern and `$x` is a variable which is used in atom to match and a template and it is why we should prefer `$x`. 

The `(let ($x $x) ($z $y) ($z $y))` example shows it clearly. `$x` here is used only to designate that `$z` and `$y` are equal. If we apply `{ $x <- $z, $y <- $z }` bindings to the `($z $y)` template the result is `($z $y)`. But if we choose `{ $y <- $x, $z <- $x }` the result is `($x $x)` which is correct and received from original expression by substituting names of the variables.

The logic is to get list of variables from atom and template and use them to replace variable equalities in `Bindings` by variable assignments.
