### ISSUE TITLE
Gracefully handle parsing errors on C API/Python side

### ISSUE THREAD

**Issue by vsbogd** [trueagi-io/hyperon-experimental#301]
After closing #273, one more thing to do is to handle parsing error results in C API, Python API and MeTTa console interpreter.
At the moment they are also lead to the panic because of unwrapping `Result` in C API layer:
https://github.com/trueagi-io/hyperon-experimental/blob/78bad1092e71eb98cd7ab254ed6e0469367be519/c/src/metta.rs#L78-L83

**Comment by luketpeterson** [comment]
I'm taking this issue as it'll get fixed as a side effect of my work on https://github.com/trueagi-io/hyperon-experimental/issues/439

**Comment by luketpeterson** [comment]
Parsing errors are now handled gracefully, through both the C and Python APIs.  When the runner calls the parser, however, the runner's C-bindings can still panic.

Therefore, I'd like to close out this issue, and work on https://github.com/trueagi-io/hyperon-experimental/issues/465
