### ISSUE TITLE
Some imports are redundant

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#305]
## Overview

Some metta file imports lead to extraneous non-determinism. 

## How to reproduce

Unpack the following archive

[folder.tar.gz](https://github.com/trueagi-io/hyperon-experimental/files/11545740/folder.tar.gz)

which contains a folder called `folder` with `A.metta`, `B.metta`, `C.metta`, `D.metta` and `E.metta` under it.

`A.metta` contains the definition of a function `foo`, while `B.metta` to `E.metta` contains various ways to import `A.metta` and call `foo`.

`B.metta` and `C.metta` are just here to show that `import!` works as expected.  Then `D.metta` fails, seemingly because of a convoluted import path of `A.metta`.  `E.metta` also fails, possibly for a different reason.

## What should normally be expected

In `D.metta` and `E.metta`, `!(foo 41)` should output only one result, `[42]`.

## What is observed instead

`D.metta` and `E.metta` outputs the result multiple times `[42, 42, 42, 42, 42, 42, 42, 42]`, indicating redundancy in the non-deterministic interpretation.

**Comment by ngeiswei** [comment]
@vsbogd, I need to have this fixed in order to move forward, so I have assigned myself to it, but if you happen to have already started to look into it and have some insights to share, please feel free to do so.

**Comment by Necr0x0Der** [comment]
> @vsbogd, I need to have this fixed in order to move forward, so I have assigned myself to it, but if you happen to have already started to look into it and have some insights to share, please feel free to do so.

Great, thanks! The core implementation is in `impl Grounded for ImportOp {` (stdlib.rs).
Also, take a look at `modules: Shared<HashMap<PathBuf, Shared<GroundingSpace>>>` in metta/runner/mod.rs .
 Feel free to ask questions if the logic behind the code is not clear.
