### ISSUE TITLE
Add interface to create custom Space implementation in Python

### ISSUE THREAD

**Issue by luketpeterson** [trueagi-io/hyperon-experimental#308]
Building on the CSpace, allow Python code to define a new Space.

**Comment by vsbogd** [comment]
One example of similar API which is already implemented is a Python `GroundedObject` class. It has a C++ `GroundedObject` adapter class in `hyperonpy.cpp` file which adapts Python successors of the `GroundedObject` to the C and Rust API: https://github.com/trueagi-io/hyperon-experimental/blob/4f9b774c90445bf5de8c50b4cc74d9c874d6970a/python/hyperonpy.cpp#L78-L95
