### ISSUE TITLE
Update conan version

### ISSUE THREAD

**Issue by Adam-Vandervorst** [trueagi-io/hyperon-experimental#311]
The conan version currently specified (1.57) in doesn't support GCC 13 (which is the default on my system now).

This also invalidates "GCC (7.5 or later)".

FWIW, Conan 2 looks a lot cleaner, but that likely has no effect on the codebase.
[The migration guide](https://docs.conan.io/1/conan_v2.html)

**Comment by vsbogd** [comment]
Adam, could you please clarify what issue do you see specifically. Do you mean conan cannot detect GCC 13? Does [this](https://github.com/trueagi-io/hyperon-experimental#conan-claims-it-cannot-find-out-the-version-of-the-c-compiler) help?
