### ISSUE TITLE
what does (: a (-> B A)) mean ?

### ISSUE THREAD

**Issue by aymeric75** [trueagi-io/hyperon-experimental#327]
I am pretty sure it's not the right place ask, but couldn't find better.

In the MeTTa specification, I have hard time understanding the -> (arrow) built-in.

For instance, what does (: a (-> B A)) mean ?

Thanks

**Comment by vsbogd** [comment]
> For instance, what does (: a (-> B A)) mean ?

Arrow is a type constructor of function types. `(-> B A)` is a type of a function with single argument of type `B` which returns value of type `A`. `(-> C B A)` is a function which gets two arguments of type `C` and `B` respectively and returns value of type `A`.

**Comment by aymeric75** [comment]
Ok very clear, thanks a lot
