### ISSUE TITLE
What does (: = (-> $t $t Type)) mean ?

### ISSUE THREAD

**Issue by aymeric75** [trueagi-io/hyperon-experimental#330]
Hello,

In section 5 of the [MeTTa spec](https://wiki.opencog.org/wikihome/images/b/b7/MeTTa_Specification.pdf) , I am not sure to understand the meaning of :

` (: = (-> $t $t Type))`

does it mean that '=' is a function that takes $t and returns $t ? but what does the Type symbol means means here ?

Best regards

Aymeric

**Comment by aymeric75** [comment]
maybe I got it: it means "=" is a function that takes $t and returns $t , and this function is a Type... no ?

**Comment by vsbogd** [comment]
Literally it means `=` is a type constructor which has two equal arguments as parameters (this is designated by using the same variable `$t` on arguments positions).

**Comment by aymeric75** [comment]
thanks!
