### ISSUE TITLE
Variable renaming in custom `match` is not identified by `case`

### ISSUE THREAD

**Issue by Necr0x0Der** [trueagi-io/hyperon-experimental#336]
In this line of code https://github.com/trueagi-io/hyperon-experimental/blob/8ee0262a1469c29094d49fd51c515646ae59a212/python/sandbox/numpy/numme.py#L39
while running this line of script https://github.com/trueagi-io/hyperon-experimental/blob/8ee0262a1469c29094d49fd51c515646ae59a212/python/sandbox/numpy/nm_test.metta#L34
the following bindings are obtained
```
{'y1': array([2, 3]), 'y2#33': array([3, 4]), 'y3': array([4, 5])}
{'x#32': array([[1, 1],
       [2, 2],
       [3, 3]]), 'y1': array([2, 3]), 'y2#33': array([3, 4]), 'y3': array([4, 5])}
```
and the result of whole evaluation `case` is `(np.add $x#32 $y2#33))`. That is, exactly those variables, which are used in the result of `case` are got renamed and not used to form the actual output (i.e. `(np.add $x $y2))`).

How to reproduce: run `python/sandbox/numpy/nm_test.metta` script.

**Comment by vsbogd** [comment]
My guess it can be an issue of passing `Bindings` between Python and Rust. But it needs more analysis to say for sure.

**Comment by vsbogd** [comment]
@Necr0x0Der  could you please retest it. May be it is fixed after switching to minimal MeTTa.

**Comment by Necr0x0Der** [comment]
Yes, it seems to be fixed (although some other minor changes in the behavior also happened)
