### ISSUE TITLE
Two different atom array types in C API

### ISSUE THREAD

**Issue by luketpeterson** [trueagi-io/hyperon-experimental#348]
The C API has two different atom array types: `atom_array_t` (used by atom callbacks) and `vec_atom_t` used by the grounded atom, space, and bindings APIs.

I believe there should only be one data structure in the API to represent an array of atoms.

I have a slight preference for vec_atom_t, but I'd be happy with either one - but I don't see a value in having multiple.

**Comment by vsbogd** [comment]
They have slightly different purposes. Historically `vec_atom_t` was introduced as a C API wrapper of the Rust dynamic array `Vec<Atom>` and `array_t` (and `atom_array_t` as its specialization)  was introduced to be transparent representation of a constantly sized array for C API clients (basically it is a pointer to array and size). In case of `*const vec_atom_t` they should be absolutely replaceable. 

I agree that there is some duplication. And I don't have a strong opinion which implementation should be kept. In fact as dynamic array case covers static array case and to implement dynamic array case we anyway need some list of interface  functions, probably we could introduce array type with such functions (or keep `vec_atom_t`) and use any implementation which works.

**Comment by luketpeterson** [comment]
Let's change the interface over to `vec_atom_t`, and as you said, pass `*const vec_atom_t` for the callback functions.

I'll do this if you agree.

**Comment by vsbogd** [comment]
Yes, I think its ok to do this change.
