### ISSUE TITLE
Need a Python API to get the hyperonpy version

### ISSUE THREAD

**Issue by luketpeterson** [trueagi-io/hyperon-experimental#417]
I need an entry point I can call from Python to get a version for the hyperonpy Python package.  Ideally the version will automatically track a version that's auto-incremented during build or publishing.

**Comment by wenwei-dev** [comment]
Run `metta --version` to print the version. Next step is to auto increase the version by commit and tag.

**Comment by luketpeterson** [comment]
I am confused.  Which binary are you talking about running?  I need an API entry point (function or object) I can call to get the version.  Ideally the version will follow semver conventions.  (https://semver.org/) with the most minor (patch) version being based on the release, and the other two being explicitly set be a human.

**Comment by luketpeterson** [comment]
The `hyperon.__version__` variable contains "0.1".  Is there any way we can make this contain a semver-compatible (major.minor.patch) version?  https://semver.org/  in my experience 2-tuple versions aren't expressive enough.

Or does Python have a different standard for version numbers to express patch releases?

**Comment by vsbogd** [comment]
> The hyperon.__version__ variable contains "0.1".

Luke, it should be `0.1.6`. The possible issue your local installed hyperon is old, it should be enough to do:
```
python -m pip install -eU ./python[dev]
```
You can also install old version before: 
```
python -m pip uninstall hyperon
```

**Comment by vsbogd** [comment]
> Next step is to auto increase the version by commit and tag.

Do you think it is necessary. At the moment the version is increased after each release. We can do it automatically in a release GitHub Action job, but I don't see if we need to increase it after each commit. I am not against it but it can take a lot of time to make sure it works properly in every environment and I am not sure it worth it. Also we have Rust library and C API library and Rust repl versions.

**Comment by luketpeterson** [comment]
> Luke, it should be `0.1.6`. The possible issue your local installed hyperon is old, it should be enough to do:

This is the hyperonpy build from source.  The hyperonpy installed in the global package registry is an `hyperon.egg-link` file that redirects to my build dir.

**Comment by vsbogd** [comment]
> Ahh. I see python caches some junk so even though the files were updated, pip's info (and the __version__ variable) wasn't

Should not be the case if you installed in editable mode, but who knows.

**Comment by vsbogd** [comment]
> It's probably not necessary to bump it after each commit. But it wouldn't hurt either

My point is bumping it can make build more complex and I would say we should do it for all components not only for Python then.

**Comment by luketpeterson** [comment]
> Should not be the case if you installed in editable mode, but who knows

Who knows.  Reinstalling with pip fix it.  Our users won't hit whatever I hit because they won't be actively developing hyperonpy.  So I'm not worried about it.

**Comment by luketpeterson** [comment]
> My point is bumping it can make build more complex and I would say we should do it for all components not only for Python then.

I don't think it's worth spending time on.  We're probably going to release every couple of months, so I don't think it's worth a complex process to automate.  Also some things are better left un-automated because it forces some conscious thought.  I always feel like dependency versioning is one of those things.

We can revisit if necessary, but otherwise I'm happy with the state of the change.

**Comment by vsbogd** [comment]
> Reinstalling with pip fix it. Our users won't hit whatever I hit because they won't be actively developing hyperonpy. 

Yes, the issue is that `hyperon.__version__` is extracted from the version of the distributive and this version changes only when new version is installed. Thus it cannot be changed via editing `pyproject.toml` in editable mode.

**Comment by luketpeterson** [comment]
I think this issue is all sorted out now.  Thanks!
