### ISSUE TITLE
Upgrade build system to Conan 2

### ISSUE THREAD

**Issue by gl-yziquel** [trueagi-io/hyperon-experimental#421]
Currently, the build system uses Conan 1.60.2. Please upgrade to Conan 2.

**Comment by vsbogd** [comment]
Hi @gl-yziquel, by default the priority of this ticket is low. Do you have some specific reason to raise it which could increase the priority?

**Comment by gl-yziquel** [comment]
No. Merely convenience.

Projects building out of the box is the best way to make them "not-unpopular".

Depending on 1.60 is a hindrance. Adds confusion.

**Comment by vsbogd** [comment]
This issue doesn't require deep understanding of the code base and is relatively small thus I marking it as `good first issue`.

**Comment by luketpeterson** [comment]
If / when we tackle https://github.com/trueagi-io/hyperon-experimental/issues/283, we *might* be able to jettison Conan completely.  But not clear when we'll undertake that work so nobody should be blocked on attempting Conan migration in the meantime.

**Comment by gl-yziquel** [comment]
Isn't Maturin an upgrade from PyO3 ?

**Comment by luketpeterson** [comment]
> Isn't Maturin an upgrade from PyO3 ?

Not exactly.  maturin is for packaging and publishing modules built in Rust with pyo3.  We might use it in the implementation of https://github.com/trueagi-io/hyperon-experimental/issues/283 but it's not a question of maturin vs. pyo3.  pyo3 is the foundation regardless.  https://github.com/PyO3/maturin

**Comment by gl-yziquel** [comment]
OK. My bad. Thank you.

I was planning on experimenting with Maturin (on other code). Thank you for clarifying the nomenclature.

**Comment by vsbogd** [comment]
> If / when we tackle https://github.com/trueagi-io/hyperon-experimental/issues/283, we might be able to jettison Conan completely.

The main reason of introducing Conan is to get third-party dependencies for the C API. C API is still planned to be a part of the project, so I think even migration to PyO3 doesn't allow us get rid of Conan.

**Comment by gl-yziquel** [comment]
I do not see the point of getting rid of conan. It seems to be one of the only mature packaging solutions for C++ code. It fits a different need than a build system like pyo3/maturin.

I'm all for pushing standardisation of packaging of C++ code. As long as it does not devolve into a religious war.

**Comment by luketpeterson** [comment]
I certainly don't have a religious ax to grind when it comes to build systems.  It's just that hyperonc's only conan dependency is on libcheck, and hyperonc's use of libcheck is very superficial.

So if hyperonpy no longer depends on pybind11 at some future time, I don't know if libcheck is enough of a reason to ask the user to install conan.  That's all.

**Comment by gl-yziquel** [comment]
I'm agnostic in this religious war.

**Comment by gl-yziquel** [comment]
Hi.

I investigated this issue a bit. Seems more tricky than it initially seemed, after some conversation I had on slack with @prince-chrimc (Chris Mc). I'll try to sum up what I cursorily understood:

Migration from conan v1 to conan v2 is usually straightforward, as it is mainly the CLI that changes. However, it is precisely the CLI invocation from the CMakeLists.txt that hyperon is using that is at stake. Namely, the `COMMAND cmake -E env CC= CXX= conan install --build -- ${CMAKE_CURRENT_SOURCE_DIR}` statement that may be found here:

https://github.com/trueagi-io/hyperon-experimental/blob/v0.1.5/c/CMakeLists.txt#L12

Roughly put, this seems to be some kind of unorthodox usage of conan.

An example of how to do it "right" would be the following:

https://github.com/conan-io/cmake-conan/tree/develop2

The cmake setup is however to complex for me to correct it on my own as of today.

Moreover, the only dependency that conan is handling has not been migrated to conan 2. Which will be a stumbling block anyhow.

https://conan.io/center/recipes/libcheck

Aside from this libcheck to conan v2 migration, here are a few changes in v2: 1. `conan_basic_setup` does not exist anymore. the `cmake` generator is changed to a `cmake_layout` layout. The `cmake` generator is 5 years old, and will be removed in v2. In the conan_provider.cmake linked below, it is CMakeDeps that is used as generator:

https://github.com/conan-io/cmake-conan/blob/develop2/conan_provider.cmake#L361

Somewhat more conceptually, it seems that the goal of the CMake setup in hyperon was to override CMake's behaviour to mimic Cargo's `crate-type = ["cdylib", "staticlib"]` behaviour:

https://github.com/trueagi-io/hyperon-experimental/blob/66c7229d21405d5791695a9927dbde6f869bef47/c/Cargo.toml#L16

ChrisMc, on Slack, states: "it would have been easier to flip this and pass in create-type=lib from the cli" cf. https://doc.rust-lang.org/reference/linkage.html

All this flies a bit over my head at the moment. But I hope this comment gives pointers and references to the issue at hand.

**Comment by vsbogd** [comment]
@gl-yziquel, thank you for the detailed analysis of the issue.

> Moreover, the only dependency that conan is handling, i.e. libcheck, has not been migrated to conan 2. 

One more place where Conan is used is [hyperonpy library](https://github.com/trueagi-io/hyperon-experimental/blob/main/python/conanfile.txt) which requires `pybind11` and `optional-lite`.

> Somewhat more conceptually, it seems that the goal of the CMake setup in hyperon was to override CMake's behaviour to mimic Cargo's crate-type = ["cdylib", "staticlib"] behaviour.

The goal of using CMake is to glue parts of the projects written with usage of different programming platforms (`lib`, `repl` in Rust, `c` in Rust and C, `python` in C++ and Python) into the single build. I tried to use only Cargo at first but I found it is cumbersome to use it for the C++ builds. I chose CMake because it is cross-platform, quite familiar to the OpenCog team and flexible enough to build all parts of the project with a single command. Conan is used as a C/C++ library package manager and I am not sure if there is better alternative.

**Comment by vsbogd** [comment]
I started working on migration to Conan 2 (see [branch](https://github.com/vsbogd/hyperon-experimental/tree/conan2)). At the moment project can be built successfully. The only complexity is it require a lot of complex commands to be built. May be the best way of doing it is using Conan instead of CMake as a build tool at the root of the project.
