### ISSUE TITLE
Tokens introduced in imported script are not used for its parsing 

### ISSUE THREAD

**Issue by Necr0x0Der** [trueagi-io/hyperon-experimental#426]
Example:

**a.metta** :
```
! (bind! &num 100)
(= (f) &num)
```

**main.metta** :
```
! (import! &self a.metta)
! (f)
! &num
```

Running **main.metta** gives `[&num], [100]`. While `&num` is replaced with `100` in **main.metta** by the tokenizer, it is not replaced in **a.metta**.
Running
**main2.metta** :
```
! (import! &a a.metta)
! (match &a (= (f) $x) $x)
! &num
```
produces the same results meaning that even if we import into a different space, the main tokenizer is modified, while the script imported into the new space is not parsed correctly.
This situation is reproduced for other ways of introducing new tokens, e.g. for `extend-py!`. If it is called within an imported script, tokens introduced by it are not used for parsing this very script.

Such cases should be taken into account for reworking imports / extensions / libraries in MeTTa.

**Comment by vsbogd** [comment]
Works correctly at the moment.
