### ISSUE TITLE
Rust will be the definitive language used for MeTTa ? On which example/project to start learning MeTTa ?

### ISSUE THREAD

**Issue by aymeric75** [trueagi-io/hyperon-experimental#441]
Hello,

I thought that MeTTa would be a full-fledged language, but from what I understand it's written in Rust ? is it a library of the Rust language ? will this be the definitive choice for programming in MeTTa ?

Side question: I wanted to start my understanding of MeTTa with the child ai example but this one is written in Python and apparently only the draft of the code is available. What example/implementation of MeTTa would you advice for a beginner to have a grasp on the language (i.e. understanding it, using it)?

Thanks a lot

Aymeric

**Comment by vsbogd** [comment]
> I thought that MeTTa would be a full-fledged language, but from what I understand it's written in Rust ? is it a library of the Rust language ? will this be the definitive choice for programming in MeTTa ?

MeTTa interpreter is written in Rust in the same way like one of the most popular Python interpreters is written in C. It doesn't mean MeTTa is a Rust library, but the MeTTa interpreter implementation is. Currently we are working on making Rust interpreter of MeTTa as small and transparent as possible and allowing implementing MeTTa interpreter using minimal MeTTa instruction set written in Rust.

> What example/implementation of MeTTa would you advice for a beginner to have a grasp on the language (i.e. understanding it, using it)?

The most relevant and up to date list of examples is published in [Overview section of the repo's README.md](https://github.com/trueagi-io/hyperon-experimental#overview).  More specifically I would recomment to look at [MeTTa test scripts](https://github.com/trueagi-io/hyperon-experimental/blob/main/python/tests/scripts) or [MeTTa examples repo](https://github.com/trueagi-io/metta-examples).

**Comment by vsbogd** [comment]
> "MeTTa currently has support for 3 extension languages: Rust, C, & Python" means MeTTa has an interpreter implemented in all of these 3 languages ?

Just to be more specific here, interpreter is implemented in Rust. And as @luketpeterson said above you can write extensions in three different languages Rust, C, Python.

**Comment by aymeric75** [comment]
All right, all clear now thanks a lot :))
