### ISSUE TITLE
README correction

### ISSUE THREAD

**Issue by CICS-Oleg** [trueagi-io/hyperon-experimental#457]
README says that Rust Language Server is the one of supported IDEs. But it is now deprecated. Should we replace this with [rust-analyzer](https://github.com/rust-lang/rust-analyzer)? I've updated README in [this](https://github.com/trueagi-io/hyperon-experimental/pull/456) PR.

**Comment by vsbogd** [comment]
Yeah, you are right, I merged PR.

**Comment by vsbogd** [comment]
Thanks!
