### ISSUE TITLE
docker image will not rebuild when code is changed.

### ISSUE THREAD

**Issue by astroseger** [trueagi-io/hyperon-experimental#460]
Dockerfile is written in such a way that it will not rebuild when something has changed in source code (because it takes source from github and docker assumes that nothing has changed).
Possible solutions (I’m not sure which one is better):

1. In README add `–no-cache` for docker build command 
2. Rewrite Dockerfile (and instruction in README) in such a way that it takes files from a local folder instead of github (via ADD command). Which might be convenient for developers.

**Comment by vsbogd** [comment]
Done
