### ISSUE TITLE
Not create .config/metta directory by default when API is used

### ISSUE THREAD

**Issue by vsbogd** [trueagi-io/hyperon-experimental#475]
MeTTa runner creates `.config/metta` directory by default and fills it by `init.metta` script when it is started for the first time even when it is called through API. But this behavior is not appropriate by the following reasons:
- it leaves environment dirty and behavior not reproducible - next time user starts MeTTa runner it expects it works the same way as at the first time, but in fact the logic will be different because some initialization files are already in filesystem. If we will change the content of the initialization files in the future the logic for a new version of MeTTa runner will be different and user is not aware of it because he or she don't know about files created
- filesystem can be non-writable - under many conditions writing files into filesystem can fail: lack of permissions or read-only disk
- it is not expected that API usage makes any changes in a filesystem without explicit asking to do it

User can expect that running command line tools creates a configuration folder and keeps some info in it, but even this is not really necessary (for example Python doesn't do it). If user wants to change an environment he can always do it explicitly. But I would suggest disabling creating `.config` directory by default when API is used.

**Comment by vsbogd** [comment]
The quickest fix I can suggest is change `no_cfg_dir` value from `false` to `true` by default.

**Comment by Necr0x0Der** [comment]
I don't have a strong opinion on automatic creation of `.config` in general (although I do agree with some points above), but I have a few remarks:
* MeTTa should be installed somewhere (even its API part including .so files, Python library, etc.);
* we may want to put there some command line tools as well (in particular, for creating environments, etc.);
* currently, `.config` has a very useful `modules` subfolder, which is available via API as well; if `.config` is not created, we should put this folder somewhere else;
* I agree that creating and loading `init.metta` is unexpected by API users, and thus it is kind of undesirable; however, I'd like the behavior to be identical for REPL and API by default, so it's maybe not the question of having `.config` or not, but not creating `metta.init` by default for both REPL and API. However, if REPL prefers to have `init.metta` it might be better just to explicitly separate REPL and API environments;
* besides `modules` (which are or will be needed by default) and `init.metta` (which may not be needed by default for API), other stuff in `.config` is relevant to REPL only (however, other command line tools may utilize this folder in the future as well). Apparently, REPL needs some config files, but maybe we just need to separate what is needed by REPL, and what is needed by core API keeping in mind that we do want to have "one metta" (parameterized by environments, though).

**Comment by vsbogd** [comment]
> currently, .config has a very useful modules subfolder, which is available via API as well; if .config is not created, we should put this folder somewhere else;

It is already possible to create and use an environment with custom include paths via API. I agree that it can be useful to have some standard location which is usable from both API and REPL (see next comment).

> I agree that creating and loading init.metta is unexpected by API users, and thus it is kind of undesirable; however, I'd like the behavior to be identical for REPL and API by default, so it's maybe not the question of having .config or not, but not creating metta.init by default for both REPL and API. However, if REPL prefers to have init.metta it might be better just to explicitly separate REPL and API environments;

I would suggest not create `.config/metta/modules` by default when API is used, but include it into include paths automatically as a compromise. I think `init.metta` should not be created nor executed when API is used, but user always can run it manually via API using standard path.

> Apparently, REPL needs some config files, but maybe we just need to separate what is needed by REPL, and what is needed by core API keeping in mind that we do want to have "one metta" (parameterized by environments, though).

They are already separated and other files under `.config/metta` directory should not be created when runner API is used. @luketpeterson please correct me if I am wrong.

**Comment by Necr0x0Der** [comment]
> I would suggest not create .config/metta/modules by default when API is used, but include it into include paths automatically as a compromise.

I hope that we will have a lot of a number of core libraries besides `stdlib`, which should be installed and be accessible via `import!` by default from API as well. Thus, I do think we need a standard location for `modules` created automatically. I don't see the reason not to create it now. I'm ok if it will have a different location than `.config/metta` since it is not a part of config, but a part of environment.  That is, I think we can move `modules` if we prefer some other location, but I'm against of removing it even as a temporary solution.

**Comment by vsbogd** [comment]
> I hope that we will have a number of core libraries besides stdlib shortly, which should be installed and be accessible via import! by default from API as well. 

My point is that it is not a MeTTa runner which should create this path. If standard libraries are installed into the system then tool which installs them should create this path. Python interpreter or C compiler doesn't create a path for a standard libraries, packaging tools doing this. If user needs it he can remove standard Python library completely and path to this library will not be created automatically. Thus MeTTa runner should be reader not writer of the standard library directory and files.

**Comment by Necr0x0Der** [comment]
> My point is that it is not a MeTTa runner which should create this path.

Yes, I agree on this, and this doesn't contradict to my suggestions.

**Comment by luketpeterson** [comment]
Cleanup.  I think this can be closed since the change has been merged.
