### ISSUE TITLE
foldl randomly fails

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#484]
This program occasionaly gives wrong result:
```
        (= (all $A)
           (foldl-atom $A True $a $b (eval (and $a $b))))
        !(all (True True True False))
```
[(foldl-atom (True True True False) True $head#1623 $b#1168 (eval (and $a#1167 $head#1677)))]

3/4 of runs i get correct result [[False]] and 1/4 the expression above

debug logs
[log_debug.txt](https://github.com/trueagi-io/hyperon-experimental/files/13243607/log_debug.txt)

interpreter steps
[log.txt](https://github.com/trueagi-io/hyperon-experimental/files/13243620/log.txt)

**Comment by Necr0x0Der** [comment]
Is it related to #461 ?

**Comment by vsbogd** [comment]
I believe here @noskill means minimal MeTTa interpreter and it is different from one which is mentioned in #461

**Comment by vsbogd** [comment]
on the other hand the root cause may be deeper, for instance in `Bindings` implementation

**Comment by vsbogd** [comment]
Should be fixed now, I cannot reproduce. @noskill could you please retest and close?

**Comment by noskill** [comment]
Yes, i can't reproduce it anymore.
