### ISSUE TITLE
println! and trace! won't print due to caching

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#486]
for example:
```
        (= (woman $X) False)
        (= (sisters (woman $X) (woman $Y)) (let $a (println! (woman $Y)) True))
        !(let $W (sisters $X $Y) (println! $Y)) 
```

prints False only ones. Can we disable caching for at least trace! since it is a debug tool?

**Comment by vsbogd** [comment]
Thanks Anatoly! Closed by https://github.com/trueagi-io/hyperon-experimental/pull/494
