### ISSUE TITLE
built-in if else operator evaluates both branches

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#496]
Consider this example:
```
(= (test2)
      (trace! trace (test2)))

!(if False False (test2) )
```

The program never stops since *if* evaluates (test2) while it shouldn't

I test on maximal metta

**Comment by noskill** [comment]
Btw where it is implemented? It's hard to find with text search

**Comment by vsbogd** [comment]
`if` is implemented in `stdlib.rs`, search for `METTA_CODE`.

Why do you think it should not fall into infinite recursion:
`(if False False (test2) ) -> (test2) -> (trace! trace (test2)) -> (test2) -> ...` ?

**Comment by noskill** [comment]
Well, it's the purpose of having conditional operator in a programming language. It should allow you to choose which computation to run.

**Comment by vsbogd** [comment]
It is `(if False ...)` thus it evaluates only `else` branch which is `(test2)`.
