### ISSUE TITLE
Error of the docker endpoint not working

### ISSUE THREAD

**Issue by Nahom32** [trueagi-io/hyperon-experimental#515]
The error results in the following description : 
This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=trueagi%2Fhyperon&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by vsbogd** [comment]
Hi @Nahom32 , could you please write steps to reproduce the issue?

**Comment by Nahom32** [comment]
@vsbogd sorry I think it was a problem with my docker not being updated!

**Comment by Nahom32** [comment]
@vsbogd I have resolved it
