### ISSUE TITLE
libpython.so cannot be found when MeTTa REPL is built under Conda environment

### ISSUE THREAD

**Issue by vsbogd** [trueagi-io/hyperon-experimental#520]
Steps to reproduce:
- create fresh conda environment
- activate environment
- setup project according to repo README.md instructions
- execute
```
$ cd ./repl
$ cargo build
$ ./target/debug/metta
```

Expected result: REPL started
Actual result:
```
./target/debug/metta: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

Library is present in environment:
```
$ find ~/miniconda3/envs/build -name libpython3.7m.so.1.0
~/miniconda3/envs/build/lib/libpython3.7m.so.1.0
```

**Comment by luketpeterson** [comment]
Isn't this a duplicate of https://github.com/trueagi-io/hyperon-experimental/issues/432 ?

**Comment by vsbogd** [comment]
You are right, I am sorry, closing it
