### ISSUE TITLE
REPL usage information

### ISSUE THREAD

**Issue by wenwei-dev** [trueagi-io/hyperon-experimental#540]
It would be very helpful to provide some usage information when the user types "help", "?", or something like that in REPL. I'm not really sure how to use REPL properly. I guess other beginners might feel the same way.

**Comment by Necr0x0Der** [comment]
Besides help, it would be nice to have `exit` command (or just a MeTTa symbol, which is interpreted by REPL as such the command)

**Comment by luketpeterson** [comment]
These are all on my todo list.  I just got busy focussed elsewhere.  https://github.com/trueagi-io/hyperon-experimental/issues/398

A man page is also a desired feature in the same vein.

**Comment by Necr0x0Der** [comment]
Closing as a duplicate
