### ISSUE TITLE
Move das-gate from sandbox to a dedicated extension folder

### ISSUE THREAD

**Issue by Necr0x0Der** [trueagi-io/hyperon-experimental#548]
We need to be able to to use das-gate extension without additional setup actions. it should be installed together with metta and `(extend-py! das-gate)` should work out-of-the-box. It's possibly enough to put it into python/hyperon folder with some simple search for modules in `hyperon.libs` by `extend-py`. If a more elaborated solution cannot be done asap, a hotfix will be implemented. @luketpeterson , is your module system going to cover `extend-py`?

**Comment by luketpeterson** [comment]
> is your module system going to cover extend-py

In the module system, both pure-metta modules and python-implemented modules (and hybrids) are all loaded and imported via `import!`.  So `extend-py` is deprecated.

However there is enough code change around the module system that I want to give it a chance to "settle" (code review, bake time, etc.) Therefore I will hotfix this for the immediate term.

**Comment by Necr0x0Der** [comment]
Hotfixed via #555
