### ISSUE TITLE
Package installation error with pip

### ISSUE THREAD

**Issue by patham9** [trueagi-io/hyperon-experimental#565]
The command
`python3 -m pip install -e ./python[dev]`
does not work anymore and instead outputs an error message
```
error: Support for editable installs via PEP 660 was recently introduced
in setuptools.
```

One can still run MeTTa from the folder, but due to the issue it will not install in the standard way anymore.

**Comment by patham9** [comment]
Interestingly it also failed for me on Ubuntu. There it did not show me the error however, instead the executable is just not available in the system path after the command.
Workaround was to symlink a sh script with content
`python3 /home/patham9/hyperon-experimental/python/hyperon/metta.py $@`
to `/usr/bin/metta`.

**Comment by vsbogd** [comment]
Hi Patrick, could you please clarify if you built the native code before installing Python library as  described in README.md:
- https://github.com/trueagi-io/hyperon-experimental#c-and-python-api
- https://github.com/trueagi-io/hyperon-experimental#running-python-and-metta-examples

At some point the order was changed, before one needed to run `pip install` before building binaries, now it is vice versa, so it is a common pitfall.

**Comment by vsbogd** [comment]
@patham9 can we close it?

**Comment by patham9** [comment]
Yes I installed the native code before installing the Python library.
The instructions in the Readme work neither on Mac OS Ventura, nor on Ubuntu 22 for me.
But the symlink workaround worked.
A few months ago it the instructions worked well.

**Comment by vsbogd** [comment]
@patham9, could you please add results of the following commands:
```
python3 --version
python3 -m pip --version
python3 -m pip list
```
and full log of the `python3 -m pip install -e ./python[dev]`

**Comment by vsbogd** [comment]
@patham9 please shout if you still can reproduce the issue. Otherwise I think we can close it.

**Comment by vsbogd** [comment]
Closing it as there is not enough  information to investigate.

**Comment by patham9** [comment]
I can try again soon, but it should be fine for now if it didn't occur for anybody else.
