### ISSUE TITLE
repl can't find hyperonpy

### ISSUE THREAD

**Issue by noskill** [trueagi-io/hyperon-experimental#571]
```../repl/target/release/metta test.metta ```

Fatal Error: ModuleNotFoundError: No module named 'hyperon'

```
python -c 'import hyperon; print(hyperon.__version__)'
```
0.1.4.15.dev382+g55f6ff8

**Comment by Necr0x0Der** [comment]
One possible reason can be if hyperonpy is built under a python version different by the version in the environment, in which repl runs

**Comment by noskill** [comment]
Indeed i installed hyperonpy in conda environment and metta repl is searching in system directories

**Comment by vsbogd** [comment]
> Indeed i installed hyperonpy in conda environment and metta repl is searching in system directories

Looks like it is a duplicate of https://github.com/trueagi-io/hyperon-experimental/issues/432 then.
@noskill could you please close it if you are agree.

**Comment by noskill** [comment]
I don't have this error "./target/debug/metta: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory"

**Comment by noskill** [comment]
closing because it's working if hyperonpy is present in PYTHONPATH
