### ISSUE TITLE
Weird bug in car-atom

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#621]
## What is the problem?

`car-atom` raises an error on some non empty expression.

## How to reproduce the problem?

Run the following code

```
!(let $s (stringToChars "ab") (car-atom $s))
```

## What would you normally expect?

```
['a']
```

## What do you get instead?

```
[(Error (car-atom ('a' 'b')) "car-atom expects a non-empty expression as an argument")]
```

## What else do you have to say?

The following

```
!(stringToChars "ab")
```

correctly outputs

```
[('a' 'b')]
```

Moreover, the following

```
!(let $s ('a' 'b') (car-atom $s))
```

also correctly outputs

```
['a']
```

But for some unknown reason, sticking the two together fails.

**Comment by Necr0x0Der** [comment]
For some reason, `stringToChars` wraps up the resulting expression into `ValueAtom`. Apparently, it should not be done this way. I'll fix it.
