### ISSUE TITLE
parse grounded operation is badly implemented

### ISSUE THREAD

**Issue by Necr0x0Der** [trueagi-io/hyperon-experimental#655]
The code is
```python
parseAtom = OperationAtom('parse', lambda s: [ValueAtom(SExprParser(str(s)[1:-1]).parse(Tokenizer()))],
                              ['String', 'Atom'], unwrap=False)
```
Apparently, the result of `parse` should not be wrapped into `ValueAtom`. Also, instead of a default tokenizer, the actual tokenizer from the runner might be more preferable. It would also be nice to add unit tests in test_stdlib.py

**Comment by Necr0x0Der** [comment]
Obviously, this test expects the result of parsing to be wrapped into `ValueAtom`, which is just wrong, so these unit tests should be fixes together with fixing implementation of `parse`. As for unit tests, we can keep them in `test_text_ops` (no need to move them to `test_stdlib`). But I'd add more tests for parsing, e.g. including grounded atoms (e.g., parsing `(A 2 "S")`), nested expressions, maybe something additionally

**Comment by DaddyWesker** [comment]
> fixes together with fixing implementation of parse

Yes, my bad. It is done.

**Comment by Necr0x0Der** [comment]
Complete by #658
