### ISSUE TITLE
Documenting how to use LLM gate and test_assist.metta

### ISSUE THREAD

**Issue by cargecla1** [trueagi-io/hyperon-experimental#710]
Hello All,

I think it will be good to create examples using LLM gate, test_assist.metta and other hyperon tools, to show how to build an agentic LLM. Will that be useful? Any thoughts?

Cheers!

**Comment by Necr0x0Der** [comment]
Hi. Examples are available in the corresponding repo:
https://github.com/zarqa-ai/metta-motto
See examples, tutorial, tests folders there. Also, a tutorial will be available on metta-lang.dev in a week or so.
As for other hyperon tools, they will also be covered by tutorials and documentation, when they are ready.

**Comment by cargecla1** [comment]
> Hi. Examples are available in the corresponding repo: https://github.com/zarqa-ai/metta-motto See examples, tutorial, tests folders there. Also, a tutorial will be available on metta-lang.dev in a week or so. As for other hyperon tools, they will also be covered by tutorials and documentation, when they are ready.

Hello @Necr0x0Der ,

That explains what I couldn't find any of this, the examples are in a different repo. Thanks for sharing this and letting me know about the new tutorail coming up on metta-lang.dev. Much appreciated.

Cheers!
