### ISSUE TITLE
Question about Unbounded/Free Variables

### ISSUE THREAD

**Issue by nworb999** [trueagi-io/hyperon-experimental#787]
I got this example working and I'm not sure how it works on a deeper level:

```
(subsumption Dog Corgi)
(subsumption Animal Dog)
(subsumption Being Animal)
(subsumption Mortal Being)

(= (type-of $x $y) (match &self (subsumption $x $y) $x))
(= (get-entity-subsumptions $x $z) (type-of $x $z))
(= (get-entity-subsumptions $x $z) (get-entity-subsumptions $x (type-of $y $z)))
(= (get-entity-subsumptions $x) (get-entity-subsumptions $a $x))

! (get-entity-subsumptions Corgi) ; [Dog, Being, Mortal, Animal]
```

What are the semantics of the unbounded/free-variable `$a` in this context compared to something like Lisp?  I believe it has something to do with unification, but I was hoping for a bit more detail.

**Comment by vsbogd** [comment]
`$a` inside `(= (get-entity-subsumptions $x) (get-entity-subsumptions $a $x))` matches the first argument of the `get-entity-subsumptions` function and gets its value. But as `$a` is not used the value is lost and so in this example `$a` is just a placeholder.

Sometimes it can be used to return information through parameter. The trivial example:
```
(= (bar A) B)
!(let $r (bar $a) ($r $a)) ; $a is equal to A because of unification
; [ (B A) ]
```
Less trivial example:
```
(= (foo $x) (let $x A B)) ; `A` should be equal to the argument `$x` of the function but it is declared in function's body not signature
!(let $r (foo $a) ($r $a)) ; `$a` receives value because it is equal to the function argument
; [ (B A) ]
!(let $r (foo C) ($r $a)) ; doesn't match because `C` is not equal to `A`
; []
```
Technically speaking when two variables are unified the interpreter checks and keeps their equality. Thus if one of them receives the value another receives it as well.

**Comment by nworb999** [comment]
amazing, thank you so much!

**Comment by vsbogd** [comment]
Closing it, please feel free to reopen if you have additional questions.

**Comment by vsbogd** [comment]
Please also see the first example [here](https://metta-lang.dev/docs/learn/tutorials/eval_intro/recursion_vars.html#a-piece-of-logic) it also illustrates this technique.
