### ISSUE TITLE
Question about duplication semantics

### ISSUE THREAD

**Issue by nasser** [trueagi-io/hyperon-experimental#798]
What are the semantics of "duplicate" assertions? If I assert e.g. `(is ball red)` multiple times I get multiple results when I `match` on it, which indicates that the individual atoms are not "interned" or deduplicated in any way -- they are fully distinct. But when I `remove-atom` just once, they all disappear, which would indicate a kind of interning/deduplication. 

```
(is ball red)
(is ball red)
(is ball red)
(is ball red)
(is ball red)

! (match &self (is ball $color) $color)

! (remove-atom &self (is ball red))

! (match &self (is ball $color) $color)
```

```
[red, red, red, red, red]
[()]
[]
```

Can you clarify what is happening?

**Comment by vsbogd** [comment]
Currently MeTTa doesn't specify this behavior, and it is implementation specific. Other implementation of the space can have different behaviour. As far as I know nobody relies on the current behavior of the default in-memory atomspace in hyperon-experimental. I agree it doesn't look very uniform, but on the other hand it allows doing manual deduplication easily.

I raised #799 to change it to more uniform. If @Necr0x0Der agree we can change this behavior. But I would like to emphasize one more time - you cannot rely on this.

**Comment by nasser** [comment]
understood -- thank you!

**Comment by vsbogd** [comment]
Closing it, @nasser please feel free to reopen if you have further questions on this.
