### ISSUE TITLE
Can't build C and Python API

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/hyperon-experimental#91]
I'm trying to build MeTTa's C API, but fail at the `cmake ..` command from https://github.com/trueagi-io/hyperon-experimental/blob/main/README.md#c-and-python-api with the following error

```
ERROR: libcheck/0.15.2: 'settings.compiler' value not defined
CMake Error at c/CMakeLists.txt:4 (include):
  include could not find load file:

    /home/nilg/Work/TrueAGI/hyperon-experimental/build/c/conanbuildinfo.cmake


CMake Error at c/CMakeLists.txt:5 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".
```

**Comment by ngeiswei** [comment]
Oh, maybe the solution of that problem is described here https://github.com/trueagi-io/hyperon-experimental/blob/main/README.md#troubleshooting

**Comment by ngeiswei** [comment]
OK, typing the following
```bash
conan profile update settings.compiler=gcc default
conan profile update settings.compiler.version=10 default
conan profile update settings.compiler.libcxx=libstdc++ default
```
got me past this error.

Now, I'm having this problem

```
Could not find NOSETESTS_EXECUTABLE using the following names: nosetests
```

But I do have `nosetests3` installed so I guess I can just create a symbolic link for it, although a better fix would be that cmake detects `nosetests3` instead I suppose.

**Comment by ngeiswei** [comment]
I've create PR #92 to address the missing `nosetests` issue in my case.

**Comment by vsbogd** [comment]
Can we close the issue after merging https://github.com/trueagi-io/hyperon-experimental/pull/92 ?

**Comment by ngeiswei** [comment]
Yes, it all works now, I can run the tests and the metta scripts.
